#!/usr/bin/perl

our %bigtextfont =
  (
   default => +{  id     => "default",
                  name   => "Default",
                  height => 3,
                  glyph  => +{
                              default => +{ decimal => -1,
                                            name    => "[glyph not found]",
                                            content => +[ "┌───┐","│ ? │","└───┘", ],
                                          },
                              " " => +{ decimal => 32,
                                        name    => "space",
                                        content => +[ " ", " ", " ", ],
                                      },
                              "A" => +{ decimal => 65,
                                        name    => "capital A",
                                        content => +[ " /\\ ","/__\\","|  |", ], },
                              "B" => +{ decimal => 66,
                                        name    => "capital B",
                                        content => +[ "|\"\\","|-<","|_/", ], },
                              "C" => +{ decimal => 67,
                                        name    => "capital C",
                                        content => +[ "/\"\\","|  ","\\_/", ], },
                              "D" => +{ decimal => 68,
                                        name    => "capital D",
                                        content => +[ "|\"\\","| ▕","|_/", ],},
                              "E" => +{ decimal => 69,
                                        name    => "capital E",
                                        content => +[ "|\"\"","|- ","|__", ],},
                              "F" => +{ decimal => 70,
                                        name    => "capital F",
                                        content => +[ "|\"\"","|- ","|  ", ],},
                              "G" => +{ decimal => 71,
                                        name    => "capital G",
                                        content => +[ "/\"\\","| _","\\_/", ],},
                              "H" => +{ decimal => 72,
                                        name    => "capital H",
                                        content => +[ "|  |","|--|","|  |", ],},
                              "I" => +{ decimal => 73,
                                        name    => "capital I",
                                        content => +[ "\"|\""," | ","_|_", ],},
                              "J" => +{ decimal => 74,
                                        name    => "capital J",
                                        content => +[ "\"\"|\"","  | ","\\/  ", ],},
                              "K" => +{ decimal => 75,
                                        name    => "capital K",
                                        content => +[ "| /","|- ","| \\", ],},
                              "L" => +{ decimal => 76,
                                        name    => "capital L",
                                        content => +[ "|  ","|  ","|__", ],},
                              "M" => +{ decimal => 77,
                                        name    => "capital M",
                                        content => +[ "|\\  /|","| \\/ |","|    |", ],},
                              "N" => +{ decimal => 78,
                                        name    => "capital N",
                                        content => +[ "|\\  |","| \\ |","|  \\|", ],},
                              "O" => +{ decimal => 79,
                                        name    => "capital O",
                                        content => +[ "/\"\"\\","|  |","\\__/", ],},
                              "P" => +{ decimal => 80,
                                        name    => "capital P",
                                        content => +[ "|\"\\","|_/","|  ", ],},
                              "Q" => +{ decimal => 81,
                                        name    => "capital Q",
                                        content => +[ "/\"\"\\","|  |","\\__X", ],},
                              "R" => +{ decimal => 82,
                                        name    => "capital R",
                                        content => +[ "|\"\\","|_/","| \\", ],},
                              "S" => +{ decimal => 83,
                                        name    => "capital S",
                                        content => +[ "(\"\\"," \\ ","\\_)", ],},
                              "T" => +{ decimal => 84,
                                        name    => "capital T",
                                        content => +[ "\"\"|\"\"","  |  ","  |  ", ],},
                              "U" => +{ decimal => 85,
                                        name    => "capital U",
                                        content => +[ "|  |","|  |","\\__//", ],},
                              "V" => +{ decimal => 86,
                                        name    => "capital V",
                                        content => +[ "|   |","\\  /"," \\/ ", ],},
                              "W" => +{ decimal => 87,
                                        name    => "capital W",
                                        content => +[ "|     |","\\  |  /"," \\/ \\/", ],},
                              "X" => +{ decimal => 88,
                                        name    => "capital X",
                                        content => +[ "\\ /"," X ","/ \\", ],},
                              "Y" => +{ decimal => 89,
                                        name    => "capital Y",
                                        content => +[ "\\ /"," | "," | ", ],},
                              "Z" => +{ decimal => 90,
                                        name    => "capital Z",
                                        content => +[ "\"\"/"," / ","/__", ],},
                              "1" => +{ decimal => 49,
                                        name    => "numeral 1",
                                        content => +[ "/| "," | ","_|_", ],},
                              "2" => +{ decimal => 50,
                                        name    => "numeral 2",
                                        content => +[ "/\")"," / ","/__", ],},
                              "3" => +{ decimal => 51,
                                        name    => "numeral 3",
                                        content => +[ "/\"\\"," -<","\\_/", ],},
                              "4" => +{ decimal => 52,
                                        name    => "numeral 4",
                                        content => +[ " /|","/_|","  |", ],},
                              "5" => +{ decimal => 53,
                                        name    => "numeral 5",
                                        content => +[ "|\"\"","\"-_","__/", ],},
                              "6" => +{ decimal => 54,
                                        name    => "numeral 6",
                                        content => +[ "/\" ","|\"\\","\\_/", ],},
                              "7" => +{ decimal => 55,
                                        name    => "numeral 7",
                                        content => +[ "\"\"/"," / ","/  ", ],},
                              "8" => +{ decimal => 56,
                                        name    => "numeral 8",
                                        content => +[ "/\"\\"," X ","\\_/", ],},
                              "9" => +{ decimal => 57,
                                        name    => "numeral 9",
                                        content => +[ "/\"|","\\_|","  |", ],},
                              "0" => +{ decimal => 48,
                                        name    => "numeral 0",
                                        content => +[ "/\"\\","|.|","\\_/", ],},
                             },
               },
  );
